"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, Eye, RotateCcw, X } from "lucide-react";

type EventRow = { id:string; fingerprint:string; level:string; category:string; error_code:string|null; title:string; message:string; route:string|null; request_id:string|null; order_id:string|null; payment_id:string|null; product_id:string|null; sku_id:string|null; occurrences:number; first_seen_at:string; last_seen_at:string; status:"open"|"investigating"|"resolved"|"ignored"; resolution_note:string|null; metadata:unknown };
type ApiError = { message?: string; request_id?: string };
const levels: Record<string,string> = { debug:"调试", info:"信息", warn:"警告", error:"错误", critical:"严重" };
const statuses: Record<string,string> = { open:"待处理", investigating:"处理中", resolved:"已解决", ignored:"已忽略" };
const categories: Record<string,string> = { products:"商品", sku:"SKU", orders:"订单", inventory:"库存", payments:"支付", recharges:"充值", balance:"余额", refund:"退款", delivery:"交付", reconciliation:"对账", notifications:"通知", email:"邮件", auth:"认证", database:"数据库", security:"安全", deployment:"部署", system:"系统", performance:"性能" };

export default function AdminSystemErrorsPage() {
  const router=useRouter(), pathname=usePathname(), initial=useSearchParams();
  const [rows,setRows]=useState<EventRow[]>([]), [count,setCount]=useState(0), [loading,setLoading]=useState(true), [error,setError]=useState("");
  const [selected,setSelected]=useState<EventRow|null>(null), [note,setNote]=useState(""), [saving,setSaving]=useState(false);
  const [level,setLevel]=useState(initial.get("level")??""), [category,setCategory]=useState(initial.get("category")??""), [status,setStatus]=useState(initial.get("status")??"");
  const [requestId,setRequestId]=useState(initial.get("requestId")??""), [businessId,setBusinessId]=useState(initial.get("orderId")??""), [page,setPage]=useState(Number(initial.get("page")??1)||1);
  const pageSize=20;
  const query=useMemo(()=>{const p=new URLSearchParams({page:String(page),pageSize:String(pageSize)}); if(level)p.set("level",level);if(category)p.set("category",category);if(status)p.set("status",status);if(requestId.trim())p.set("requestId",requestId.trim());if(businessId.trim())p.set("orderId",businessId.trim());return p.toString();},[businessId,category,level,page,requestId,status]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/admin/system-errors?${query}`,{cache:"no-store"});const body=await response.json().catch(()=>null) as {events?:EventRow[];count?:number;error?:ApiError}|null;if(!response.ok)throw new Error(errorMessage(body?.error,response));setRows(body?.events??[]);setCount(body?.count??0);}catch(caught){setRows([]);setCount(0);setError(caught instanceof Error?caught.message:"异常事件加载失败，请稍后重试。");}finally{setLoading(false);}},[query]);
  useEffect(()=>{router.replace(`${pathname}?${query}`,{scroll:false});void load();},[load,pathname,query,router]);
  useEffect(()=>{setNote(selected?.resolution_note??"");},[selected]);
  async function updateStatus(next:EventRow["status"]){if(!selected||saving)return;if((next==="resolved"||next==="ignored")&&!note.trim()){setError("标记已解决或已忽略时必须填写处理说明。");return;}setSaving(true);setError("");try{const response=await fetch("/api/admin/system-errors",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,status:next,resolutionNote:note})});const body=await response.json().catch(()=>null) as {event?:EventRow;error?:ApiError}|null;if(!response.ok)throw new Error(errorMessage(body?.error,response));if(body?.event){setSelected(body.event);setRows(current=>current.map(row=>row.id===body.event?.id?body.event:row));}}catch(caught){setError(caught instanceof Error?caught.message:"状态更新失败，请稍后重试。");}finally{setSaving(false);}}
  const pages=Math.max(1,Math.ceil(count/pageSize));
  return <section className="flex h-full min-h-0 flex-1 flex-col overflow-hidden px-4 py-3 lg:px-5 lg:py-4">
    <header className="mb-3 flex shrink-0 items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-950">异常中心</h1><p className="mt-1 text-sm text-slate-500">查看经过脱敏聚合的系统异常，并记录处理状态。</p></div><button type="button" onClick={()=>void load()} className="inline-flex h-10 items-center gap-2 rounded-lg border bg-white px-4 text-sm"><RotateCcw className="h-4 w-4"/>刷新</button></header>
    <div className="flex min-h-0 flex-1 flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm">
      <div className="grid shrink-0 grid-cols-1 gap-2 border-b p-3 sm:grid-cols-2 xl:grid-cols-6">
        <select value={level} onChange={e=>{setLevel(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-3 text-sm"><option value="">全部级别</option>{Object.entries(levels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
        <select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-3 text-sm"><option value="">全部分类</option>{Object.entries(categories).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
        <select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="h-10 rounded-lg border px-3 text-sm"><option value="">全部状态</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
        <input value={requestId} onChange={e=>{setRequestId(e.target.value);setPage(1)}} placeholder="Request ID" className="h-10 rounded-lg border px-3 text-sm"/>
        <input value={businessId} onChange={e=>{setBusinessId(e.target.value);setPage(1)}} placeholder="订单 ID" className="h-10 rounded-lg border px-3 text-sm"/>
        <button type="button" onClick={()=>{setLevel("");setCategory("");setStatus("");setRequestId("");setBusinessId("");setPage(1)}} className="h-10 rounded-lg border text-sm">重置</button>
      </div>
      {error?<div role="alert" className="m-3 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
      <div className="min-h-0 flex-1 overflow-auto"><table className="min-w-[1100px] w-full text-sm"><thead className="sticky top-0 bg-slate-50 text-left text-xs text-slate-500"><tr>{["级别","分类","异常","Request ID","次数","最后出现","关联业务","状态","操作"].map(h=><th key={h} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={9} className="h-64 text-center text-slate-500">正在加载异常记录…</td></tr>:rows.length===0?<tr><td colSpan={9} className="h-64 text-center"><AlertTriangle className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-2 text-slate-500">暂无异常记录</p></td></tr>:rows.map(row=><tr key={row.id} className="hover:bg-slate-50"><td className="px-3 py-2 font-medium">{levels[row.level]??row.level}</td><td className="px-3 py-2">{categories[row.category]??row.category}</td><td className="max-w-[300px] px-3 py-2"><div className="truncate font-medium" title={row.title}>{row.title}</div><div className="truncate text-xs text-slate-500" title={row.message}>{row.message}</div></td><td className="max-w-[180px] truncate px-3 py-2 font-mono text-xs">{row.request_id??"—"}</td><td className="px-3 py-2">{row.occurrences}</td><td className="whitespace-nowrap px-3 py-2 text-xs">{formatDate(row.last_seen_at)}</td><td className="px-3 py-2">{businessLink(row)}</td><td className="px-3 py-2">{statuses[row.status]??row.status}</td><td className="px-3 py-2"><button type="button" onClick={()=>setSelected(row)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Eye className="h-3.5 w-3.5"/>查看</button></td></tr>)}</tbody></table></div>
      <footer className="flex h-12 shrink-0 items-center justify-between border-t px-3 text-sm text-slate-500"><span>共 {count} 条，第 {page}/{pages} 页</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="rounded border px-3 py-1 disabled:opacity-40">上一页</button><button disabled={page>=pages} onClick={()=>setPage(v=>Math.min(pages,v+1))} className="rounded border px-3 py-1 disabled:opacity-40">下一页</button></div></footer>
    </div>
    {selected?<div className="fixed inset-0 z-50 flex justify-end bg-slate-950/30" onClick={()=>setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-5 shadow-xl" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-lg font-semibold">异常详情</h2><p className="text-sm text-slate-500">仅展示安全摘要。</p></div><button aria-label="关闭" onClick={()=>setSelected(null)}><X className="h-5 w-5"/></button></div><div className="mt-5 space-y-3 text-sm"><Detail label="标题" value={selected.title}/><Detail label="安全摘要" value={selected.message}/><Detail label="错误代码" value={selected.error_code??"—"}/><Detail label="路由" value={selected.route??"—"}/><Detail label="Request ID" value={selected.request_id??"—"}/><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="处理说明（解决或忽略时必填）" className="w-full rounded-lg border p-3"/><div className="flex flex-wrap gap-2">{(["investigating","resolved","ignored","open"] as const).map(v=><button key={v} disabled={saving} onClick={()=>void updateStatus(v)} className="rounded border px-3 py-2 text-sm disabled:opacity-50">标记为{statuses[v]}</button>)}</div></div></aside></div>:null}
  </section>;
}

function errorMessage(error:ApiError|undefined,response:Response){const message=error?.message||"请求失败，请稍后重试。";const id=error?.request_id||response.headers.get("X-Request-ID");return id?`${message}（参考编号：${id.slice(0,12)}）`:message;}
function formatDate(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?"—":date.toLocaleString("zh-CN",{hour12:false});}
function Detail({label,value}:{label:string;value:string}){return <div className="rounded-lg border p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 break-words">{value}</div></div>;}
function businessLink(row:EventRow){if(row.order_id)return <Link className="text-orange-600" href={`/admin/orders?orderId=${row.order_id}`}>订单</Link>;if(row.payment_id)return <Link className="text-orange-600" href={`/admin/payments?paymentId=${row.payment_id}`}>支付</Link>;if(row.product_id)return <Link className="text-orange-600" href={`/admin/products?productId=${row.product_id}`}>商品</Link>;return "—";}
