-- Jianlian Shop profiles and role base
-- Run in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  phone text,
  role text not null default 'user'
    check (role in ('user', 'admin', 'support', 'finance')),
  balance numeric(12, 2) not null default 0,
  promotion_balance numeric(12, 2) not null default 0,
  invite_code text unique,
  referred_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles
add column if not exists promotion_balance numeric(12, 2) not null default 0;

alter table public.profiles
add column if not exists invite_code text;

alter table public.profiles
add column if not exists referred_by uuid references public.profiles(id) on delete set null;

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_email_idx on public.profiles(email);
create unique index if not exists profiles_invite_code_unique_idx
on public.profiles(invite_code)
where invite_code is not null;
create index if not exists profiles_invite_code_idx on public.profiles(invite_code);
create index if not exists profiles_referred_by_idx on public.profiles(referred_by);

alter table public.profiles enable row level security;

create or replace function public.role_for_email(user_email text)
returns text
language sql
immutable
as $$
  select case
    when lower(coalesce(user_email, '')) = 'gac000189@gmail.com' then 'admin'
    else 'user'
  end
$$;

create or replace function public.current_user_role(user_id uuid)
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from public.profiles where id = user_id
$$;

create or replace function public.is_admin(user_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = user_id and role = 'admin'
  )
$$;

create or replace function public.invite_code_for_user(user_id uuid)
returns text
language sql
immutable
as $$
  select 'JL' || upper(substr(md5(user_id::text), 1, 6))
$$;

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_updated_at on public.profiles;
create trigger profiles_updated_at
before update on public.profiles
for each row execute function public.handle_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  inviter_profile_id uuid;
  submitted_invite_code text;
begin
  submitted_invite_code := nullif(trim(new.raw_user_meta_data->>'invite_code'), '');

  if submitted_invite_code is not null then
    select id into inviter_profile_id
    from public.profiles
    where lower(invite_code) = lower(submitted_invite_code)
      and id <> new.id
    limit 1;
  end if;

  insert into public.profiles (
    id,
    email,
    phone,
    role,
    invite_code,
    referred_by
  )
  values (
    new.id,
    lower(new.email),
    new.phone,
    public.role_for_email(new.email),
    public.invite_code_for_user(new.id),
    inviter_profile_id
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

update public.profiles
set role = 'admin'
where lower(coalesce(email, '')) in (
  'gac000189@gmail.com'
);

update public.profiles
set role = 'user'
where lower(coalesce(email, '')) in (
  '2796692142@qq.com'
);

update public.profiles
set invite_code = public.invite_code_for_user(id)
where invite_code is null;

create table if not exists public.promotion_visits (
  id bigint generated by default as identity primary key,
  inviter_id uuid not null references public.profiles(id) on delete cascade,
  visitor_key text not null,
  created_at timestamptz not null default now(),
  unique (inviter_id, visitor_key)
);

create index if not exists promotion_visits_inviter_idx
on public.promotion_visits(inviter_id);

alter table public.promotion_visits enable row level security;

create table if not exists public.promotion_commissions (
  id uuid primary key default gen_random_uuid(),
  inviter_id uuid not null references public.profiles(id) on delete cascade,
  referred_user_id uuid references public.profiles(id) on delete set null,
  referred_user_label text,
  paid_at timestamptz not null default now(),
  recharge_amount numeric(12, 2) not null default 0,
  commission_amount numeric(12, 2) not null default 0,
  status text not null default 'confirmed'
    check (status in ('pending', 'confirmed', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists promotion_commissions_inviter_idx
on public.promotion_commissions(inviter_id, paid_at desc);

alter table public.promotion_commissions enable row level security;

create table if not exists public.promotion_withdrawals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12, 2) not null,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists promotion_withdrawals_user_idx
on public.promotion_withdrawals(user_id, created_at desc);

alter table public.promotion_withdrawals enable row level security;

create or replace function public.record_promotion_visit(
  input_invite_code text,
  input_visitor_key text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  inviter_profile_id uuid;
begin
  if nullif(trim(input_invite_code), '') is null
    or nullif(trim(input_visitor_key), '') is null then
    return;
  end if;

  select id into inviter_profile_id
  from public.profiles
  where lower(invite_code) = lower(trim(input_invite_code))
  limit 1;

  if inviter_profile_id is null then
    return;
  end if;

  insert into public.promotion_visits (inviter_id, visitor_key)
  values (inviter_profile_id, input_visitor_key)
  on conflict (inviter_id, visitor_key) do nothing;
end;
$$;

grant execute on function public.record_promotion_visit(text, text)
to anon, authenticated;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles for insert
to authenticated
with check (
  auth.uid() = id
  and email = auth.jwt()->>'email'
  and role = public.role_for_email(auth.jwt()->>'email')
);

drop policy if exists "Users can update own non-role profile" on public.profiles;
create policy "Users can update own non-role profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id and role = public.current_user_role(auth.uid()));

drop policy if exists "Users can view own promotion visits" on public.promotion_visits;
create policy "Users can view own promotion visits"
on public.promotion_visits for select
to authenticated
using (auth.uid() = inviter_id);

drop policy if exists "Users can view own promotion commissions" on public.promotion_commissions;
create policy "Users can view own promotion commissions"
on public.promotion_commissions for select
to authenticated
using (auth.uid() = inviter_id);

drop policy if exists "Users can create own withdrawal requests" on public.promotion_withdrawals;
create policy "Users can create own withdrawal requests"
on public.promotion_withdrawals for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can view own withdrawal requests" on public.promotion_withdrawals;
create policy "Users can view own withdrawal requests"
on public.promotion_withdrawals for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Admins can view all profiles" on public.profiles;
create policy "Admins can view all profiles"
on public.profiles for select
to authenticated
using (public.is_admin(auth.uid()));

drop policy if exists "Admins can update all profiles" on public.profiles;
create policy "Admins can update all profiles"
on public.profiles for update
to authenticated
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));
