export type ConsistencySeverity = "P0" | "P1" | "P2" | "P3";

export type ConsistencyRule = {
  code: string;
  category: "orders_payments" | "recharges_balance" | "refunds" | "inventory_delivery";
  title: string;
  target: string;
  normalCondition: string;
  abnormalCondition: string;
  severity: ConsistencySeverity;
  suggestion: string;
};

export const CONSISTENCY_RULES: ConsistencyRule[] = [
  {
    code: "OP-001",
    category: "orders_payments",
    title: "已支付订单缺少成功支付记录",
    target: "orders + order_payments/payment_sessions",
    normalCondition: "payment_status=paid 的订单至少存在一条成功支付记录或已支付会话",
    abnormalCondition: "订单显示已支付，但没有 paid 的支付记录或支付会话",
    severity: "P0",
    suggestion: "核对订单支付 RPC、支付会话和渠道对账记录；不得直接手改订单金额或支付状态。",
  },
  {
    code: "OP-002",
    category: "orders_payments",
    title: "支付成功但订单仍待支付",
    target: "order_payments/payment_sessions + orders",
    normalCondition: "成功支付应同步订单 payment_status 和订单状态",
    abnormalCondition: "存在 paid 支付记录，但订单仍为 pending_payment 或 unpaid",
    severity: "P0",
    suggestion: "运行支付对账并检查订单支付成功服务，避免重复入账。",
  },
  {
    code: "OP-003",
    category: "orders_payments",
    title: "订单金额与支付金额不一致",
    target: "orders.total_amount + payment amount",
    normalCondition: "同币种下订单金额与成功支付金额一致，使用两位精度比较",
    abnormalCondition: "同币种成功支付金额与订单实付金额不一致",
    severity: "P0",
    suggestion: "核对服务端金额计算、支付回调金额校验和订单快照。",
  },
  {
    code: "OP-004",
    category: "orders_payments",
    title: "订单币种与支付币种不一致",
    target: "orders.currency + payment currency",
    normalCondition: "订单和成功支付记录币种一致",
    abnormalCondition: "成功支付记录币种与订单币种不同",
    severity: "P1",
    suggestion: "检查渠道币种配置和回调币种映射，不同币种不得直接比较金额。",
  },
  {
    code: "OP-005",
    category: "orders_payments",
    title: "渠道交易号关联多个订单",
    target: "provider transaction id",
    normalCondition: "一个渠道交易号只能归属一个业务订单",
    abnormalCondition: "同一渠道交易号出现在多个订单支付记录或会话中",
    severity: "P0",
    suggestion: "冻结自动处理，人工核对 Provider 原始后台和本站支付记录。",
  },
  {
    code: "OP-006",
    category: "orders_payments",
    title: "单个订单存在多个成功支付记录",
    target: "order_payments/payment_sessions",
    normalCondition: "一个订单只能有一个有效成功支付结果",
    abnormalCondition: "同一订单存在多条 paid 支付记录或支付会话",
    severity: "P0",
    suggestion: "检查支付幂等键和回调重复处理日志，避免重复入账或重复履约。",
  },
  {
    code: "OP-007",
    category: "orders_payments",
    title: "取消订单仍存在有效支付会话",
    target: "orders + payment_sessions",
    normalCondition: "取消或关闭订单不应保留 pending/processing 且未过期支付会话",
    abnormalCondition: "cancelled/closed 订单仍有有效未过期会话",
    severity: "P1",
    suggestion: "使用已有关单服务关闭未支付会话，不要直接更新会话表。",
  },
  {
    code: "RB-001",
    category: "recharges_balance",
    title: "充值成功但缺少入账流水",
    target: "account_recharges + balance_transactions",
    normalCondition: "succeeded/paid 充值必须有一条充值入账流水",
    abnormalCondition: "充值已成功但没有对应 balance transaction",
    severity: "P0",
    suggestion: "检查 complete_account_recharge RPC 和支付完成分发服务。",
  },
  {
    code: "RB-002",
    category: "recharges_balance",
    title: "失败充值生成余额流水",
    target: "account_recharges + balance_transactions",
    normalCondition: "failed/expired/closed 充值不得生成充值入账流水",
    abnormalCondition: "失败或关闭充值存在入账流水",
    severity: "P0",
    suggestion: "人工核对余额流水来源，禁止直接删除流水或手调余额。",
  },
  {
    code: "RB-003",
    category: "recharges_balance",
    title: "同一充值重复入账",
    target: "balance_transactions.business_id",
    normalCondition: "同一充值业务只能生成一条成功入账流水",
    abnormalCondition: "同一 recharge id/recharge no 存在多条充值入账流水",
    severity: "P0",
    suggestion: "检查充值 RPC 幂等约束和回调重复处理。",
  },
  {
    code: "RB-004",
    category: "recharges_balance",
    title: "余额流水引用不存在的充值",
    target: "balance_transactions + account_recharges",
    normalCondition: "充值入账流水必须能关联到真实充值单",
    abnormalCondition: "流水 business_id 指向不存在的充值记录",
    severity: "P1",
    suggestion: "核对历史迁移数据，不要用流水倒推覆盖当前余额。",
  },
  {
    code: "RB-005",
    category: "recharges_balance",
    title: "充值金额与入账金额不一致",
    target: "account_recharges + balance_transactions",
    normalCondition: "充值 credited/received amount 与入账流水金额一致",
    abnormalCondition: "同币种充值金额与入账流水金额不一致",
    severity: "P1",
    suggestion: "检查手续费、到账金额和余额币种规则。",
  },
  {
    code: "RB-006",
    category: "recharges_balance",
    title: "余额前后值不连续",
    target: "balance_transactions",
    normalCondition: "同一用户流水 balance_after 应等于下一条流水 balance_before",
    abnormalCondition: "余额流水链路断裂或账户余额与最后流水不一致",
    severity: "P1",
    suggestion: "人工核对余额调整记录和入账 RPC，不得直接覆盖余额。",
  },
  {
    code: "RF-001",
    category: "refunds",
    title: "退款金额超过订单实付金额",
    target: "refunds + orders",
    normalCondition: "成功和处理中退款累计不得超过订单实付金额",
    abnormalCondition: "退款累计超过订单 total_amount",
    severity: "P0",
    suggestion: "暂停该订单退款处理，核对退款记录和支付渠道后台。",
  },
  {
    code: "RF-002",
    category: "refunds",
    title: "退款成功但缺少余额退款流水",
    target: "refunds + balance_transactions",
    normalCondition: "余额退款成功必须有对应余额流水",
    abnormalCondition: "余额退款成功但没有退款流水",
    severity: "P1",
    suggestion: "检查余额退款事务，区分外部退款和余额退款。",
  },
  {
    code: "RF-003",
    category: "refunds",
    title: "退款币种与订单币种不一致",
    target: "refunds + orders",
    normalCondition: "退款币种应与原订单支付币种一致",
    abnormalCondition: "退款记录币种与订单币种不同",
    severity: "P1",
    suggestion: "检查退款渠道配置和币种映射。",
  },
  {
    code: "ID-001",
    category: "inventory_delivery",
    title: "同一库存被重复预留",
    target: "digital_inventory reservation",
    normalCondition: "一条库存只能被一个有效订单预留",
    abnormalCondition: "同一库存关联多个 reserved 订单或交付记录",
    severity: "P0",
    suggestion: "检查库存预留事务和订单取消释放逻辑，禁止自动重分配。",
  },
  {
    code: "ID-002",
    category: "inventory_delivery",
    title: "同一库存被重复交付",
    target: "order_deliveries + digital_inventory",
    normalCondition: "一条数字库存只能交付给一个订单项一次",
    abnormalCondition: "同一库存出现多条 delivered 交付记录",
    severity: "P0",
    suggestion: "核对重复回调和自动发货幂等记录。",
  },
  {
    code: "ID-003",
    category: "inventory_delivery",
    title: "已交付库存缺少交付记录",
    target: "digital_inventory + order_deliveries",
    normalCondition: "delivered 库存必须存在对应交付记录",
    abnormalCondition: "库存状态 delivered 但找不到交付记录",
    severity: "P1",
    suggestion: "检查历史交付迁移或交付日志，不输出库存原文。",
  },
  {
    code: "ID-004",
    category: "inventory_delivery",
    title: "交付记录引用可用库存",
    target: "order_deliveries + digital_inventory.status",
    normalCondition: "已交付记录引用的库存状态不能是 available",
    abnormalCondition: "交付记录仍指向 available 库存",
    severity: "P0",
    suggestion: "人工核对库存状态，已交付库存不得恢复可售。",
  },
  {
    code: "ID-005",
    category: "inventory_delivery",
    title: "预留库存缺少有效订单",
    target: "digital_inventory.reserved",
    normalCondition: "reserved 库存必须关联 pending/paid/processing 等有效订单",
    abnormalCondition: "reserved 库存没有订单，或订单已取消/退款/失败",
    severity: "P1",
    suggestion: "使用已有库存释放服务处理，禁止直接 SQL 更新库存。",
  },
  {
    code: "ID-006",
    category: "inventory_delivery",
    title: "数字库存跨 SKU 关联",
    target: "digital_inventory + order_items",
    normalCondition: "多 SKU 商品交付库存 sku_id 必须与订单项 sku_id 一致",
    abnormalCondition: "库存 sku_id 与订单项 sku_id 不一致",
    severity: "P0",
    suggestion: "停止自动补发，核对 SKU 快照和库存批次。",
  },
  {
    code: "ID-007",
    category: "inventory_delivery",
    title: "订单数量与交付数量不一致",
    target: "order_items + order_deliveries",
    normalCondition: "需要数字交付的订单项交付数量应匹配购买数量",
    abnormalCondition: "已支付或已发货订单交付数量少于订单项数量或重复超出",
    severity: "P1",
    suggestion: "检查交付记录，必要时通过人工补发服务处理。",
  },
];

export function getConsistencyRule(code: string) {
  return CONSISTENCY_RULES.find((rule) => rule.code === code) ?? null;
}
