export type AdminCatalogProductType = "all" | "single_product" | "multi_sku";
export type AdminCatalogSkuStatus = "any" | "has_active_sku" | "all_draft" | "has_sold_out_sku" | "no_active_sku";
export type AdminCatalogStockLevel = "all" | "zero_stock" | "low_stock" | "in_stock";
export type AdminCatalogSupplierBinding = "all" | "supplier_bound" | "supplier_unbound";
export type AdminCatalogSupplierStock = "all" | "unknown" | "fresh" | "stale" | "error";
export type AdminCatalogInventoryVerification = "all" | "requires_verification" | "no_verification_flag";
export type AdminCatalogFulfillmentHealth = "all" | "ready" | "blocked" | "attention" | "no_source";
export type AdminCatalogOperationFilters = {
  search: string;
  productType: AdminCatalogProductType;
  productStatus: "all" | "draft" | "active" | "inactive" | "sold_out";
  deliveryType: "all" | "manual" | "automatic" | "shipping";
  skuStatus: AdminCatalogSkuStatus;
  stockLevel: AdminCatalogStockLevel;
  supplierBinding: AdminCatalogSupplierBinding;
  supplierStock: AdminCatalogSupplierStock;
  inventoryVerification: AdminCatalogInventoryVerification;
  fulfillmentHealth: AdminCatalogFulfillmentHealth;
  sortBy: "sort_order" | "updated_at";
  page: number;
  pageSize: number;
};
export type AdminProductOperationalSummary = {
  sku_total: number;
  sku_active: number;
  sku_draft: number;
  sku_sold_out: number;
  effective_stock: number;
  supplier_unbound: number;
  supplier_bound: boolean;
  requires_verification: number;
  supplier_stock_unknown: number;
  supplier_stock_fresh: number;
  supplier_stock_stale: number;
  supplier_stock_error: number;
  fulfillment_ready: number;
  fulfillment_attention: number;
  fulfillment_blocked: number;
  fulfillment_unknown: number;
  fulfillment_no_source: number;
  local_inventory_available: number;
  inventory_diagnostics_failed: boolean;
};
export const ADMIN_CATALOG_FILTER_VALUES: Readonly<Record<string, readonly string[]>>;
export const DEFAULT_ADMIN_CATALOG_FILTERS: Readonly<AdminCatalogOperationFilters>;
export function parseAdminCatalogOperationFilters(params: Pick<URLSearchParams, "get">): { ok: boolean; invalid: string[]; filters: AdminCatalogOperationFilters };
export function serializeAdminCatalogFilterState(state: Record<string, unknown>): URLSearchParams;
export function getSupplierOperationalStockState(metadata: unknown): "unknown" | "fresh" | "stale" | "error";
export function buildAdminProductOperationalSummary(product: Record<string, unknown>, skuRows?: Array<Record<string, unknown>>, inventoryContext?: { availableBySku?: Record<string, number>; error?: boolean }): AdminProductOperationalSummary;
export function hasOperationalScanFilters(filters: AdminCatalogOperationFilters): boolean;
export function matchesAdminCatalogOperations(product: Record<string, unknown>, summary: AdminProductOperationalSummary, filters: AdminCatalogOperationFilters): boolean;
export function decorateAdminCatalogProducts(products: Array<Record<string, unknown>>, skuRows: Array<Record<string, unknown>>, filters: AdminCatalogOperationFilters, inventoryContext?: { availableBySku?: Record<string, number>; error?: boolean }): Array<Record<string, unknown> & { operational_summary: AdminProductOperationalSummary }>;
export function filterAndPaginateAdminCatalogProducts(products: Array<Record<string, unknown>>, skuRows: Array<Record<string, unknown>>, filters: AdminCatalogOperationFilters, inventoryContext?: { availableBySku?: Record<string, number>; error?: boolean }): { products: Array<Record<string, unknown> & { operational_summary: AdminProductOperationalSummary }>; count: number };
