import test from 'node:test';
import assert from 'node:assert/strict';
import {timingSafeEqual,randomUUID} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {loadTs} from '../helpers/payment-session-guard-harness.mjs';
import * as policy from '../../lib/payments/snpay-reconciliation-policy.mjs';
import {runSnpayReconciliationWatcher} from '../../lib/payments/snpay-reconciliation-watcher.mjs';
import {readinessStatus,parseConfig} from '../../scripts/ops/snpay-reconciliation-readiness.mjs';
const now=Date.parse('2026-01-01T01:00:00Z'),id='10000000-0000-4000-8000-000000000003';
const envKeys=['PAYMENT_RECONCILIATION_SECRET','INTERNAL_API_SECRET','INTERNAL_JOB_SECRET','SNPAY_RECONCILIATION_EXECUTE_ENABLED'];
async function isolatedEnv(values,fn){const old=Object.fromEntries(envKeys.map(k=>[k,process.env[k]]));try{for(const k of envKeys){if(values[k]===undefined)delete process.env[k];else process.env[k]=values[k];}return await fn();}finally{for(const k of envKeys){if(old[k]===undefined)delete process.env[k];else process.env[k]=old[k];}}}
function route(service){return loadTs('app/api/internal/payments/snpay-reconciliation/route.ts',{'node:crypto':{timingSafeEqual},'next/server':{NextResponse:{json:Response.json}},'@/lib/payments/snpay-reconciliation-service':{reconcileSnpaySession:service},'@/lib/security/rate-limit':{checkRequestSize:()=>null,checkRateLimit:()=>({allowed:true}),getInternalTaskRateLimitKey:()=>''}});}
const request=(secret='CI-INTERNAL-NOT-REAL',execute=true)=>new Request('http://localhost/internal',{method:'POST',headers:secret?{'x-payment-reconciliation-secret':secret}:{},body:JSON.stringify({sessionId:id,execute})});
function realServiceFixture({state='expired',paid=true,evidence={}}={}){
 const s={id,session_no:'PS-CI',business_id:'10000000-0000-4000-8000-000000000002',business_no:'RC-CI',user_id:'CI-USER',business_type:'recharge',provider:'snpay',channel_code:'wechat',currency:'CNY',payable_amount:1,status:state,created_at:'2026-01-01T00:00:00Z',expires_at:'2026-01-01T00:15:00Z',provider_order_no:'CI-TX',last_synced_at:null,updated_at:'2026-01-01T00:00:01Z'};
 const r={id:s.business_id,recharge_no:s.business_no,user_id:s.user_id,provider:s.provider,channel_code:s.channel_code,currency:s.currency,payable_amount:1,status:state,created_at:s.created_at,expires_at:s.expires_at,credited_amount:0,completed_at:null};
 const stats={queries:0,completions:0,balance:29,ledger:0,writes:0};
 const client={from(table){const rows=table==='payment_sessions'?[s]:table==='account_recharges'?[r]:[];let operation=null;const filters=[];const q={select(){return q;},eq(k,v){filters.push(x=>x[k]===v);return q;},in(k,v){filters.push(x=>v.includes(x[k]));return q;},is(k,v){filters.push(x=>x[k]===v);return q;},update(v){operation=v;return q;},upsert(){operation={};return q;},async result(single){const matched=rows.filter(x=>filters.every(f=>f(x)));if(operation){stats.writes++;matched.forEach(x=>Object.assign(x,operation));}return{data:single?matched[0]??null:matched,error:null};},maybeSingle(){return q.result(true);},then(a,b){return q.result(false).then(a,b);}};return q;}};
 const service=loadTs('lib/payments/snpay-reconciliation-service.ts',{'node:crypto':{randomUUID},'@/lib/payments/complete-payment-service':{completePayment:async()=>{stats.completions++;assert.equal(s.status,state);s.status='paid';r.status='paid';r.credited_amount=1;r.completed_at='CI-COMPLETE';stats.balance+=1;stats.ledger++;return{idempotent:false};}},'@/lib/payments/providers':{resolveProviderForExistingSession:()=>{throw Error('REAL_PROVIDER_FORBIDDEN');}},'@/lib/supabase/service-role':{getSupabaseServiceRoleClient:()=>client},'@/lib/payments/snpay-reconciliation-policy.mjs':policy}).reconcileSnpaySession;
 const query=async()=>{stats.queries++;return{found:true,paid,status:paid?'paid':'pending',currency:'CNY',amount:1,providerChannel:'wechat',providerTransactionId:'CI-TX',paidAt:paid?'2026-01-01T00:09:00Z':null,rawSummary:{outTradeNo:'PS-CI'},rawSummarySafe:{signatureVerified:true,timestampVerified:true,identityVerified:true},...evidence};};
 return {stats,call:options=>service(options,{client,query,nowMs:now})};
}
for(const gate of [undefined,'false','0','no','garbage','TRUE',' true','true '])test(`app execute gate ${String(gate)} rejects before query/completion`,()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:gate},async()=>{const f=realServiceFixture();assert.equal((await route(f.call).POST(request())).status,403);assert.equal(f.stats.queries,0);assert.equal(f.stats.completions,0);assert.equal(f.stats.writes,0);}));
for(const secret of [null,'WRONG'])test(`enabled app rejects ${secret??'missing'} internal secret before work`,()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture();assert.equal((await route(f.call).POST(request(secret))).status,403);assert.equal(f.stats.queries,0);assert.equal(f.stats.writes,0);}));
test('INTERNAL_JOB_SECRET is not a reconciliation auth alias',()=>isolatedEnv({INTERNAL_JOB_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture();assert.equal((await route(f.call).POST(request())).status,403);assert.equal(f.stats.queries,0);}));
test('documented INTERNAL_API_SECRET fallback authenticates only when primary is absent',()=>isolatedEnv({INTERNAL_API_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'false'},async()=>{const f=realServiceFixture();assert.equal((await route(f.call).POST(request(undefined,false))).status,200);assert.equal(f.stats.queries,1);assert.equal(f.stats.writes,0);}));
test('enabled app with authenticated dry-run queries paid evidence but never writes/completes',()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture();const response=await route(f.call).POST(request(undefined,false));assert.equal((await response.json()).kind,'would_complete');assert.equal(f.stats.queries,1);assert.equal(f.stats.completions,0);assert.equal(f.stats.writes,0);}));
for(const state of ['pending','processing','expired'])test(`all gates: ${state} paid evidence completes once; replay excluded`,()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture({state}),api=route(f.call);assert.equal((await(await api.POST(request())).json()).completed,true);assert.equal((await(await api.POST(request())).json()).queried,false);assert.equal(f.stats.queries,1);assert.equal(f.stats.completions,1);assert.equal(f.stats.balance,30);assert.equal(f.stats.ledger,1);}));
for(const state of ['failed','closed','paid'])test(`terminal ${state} excludes query/completion`,()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture({state});await route(f.call).POST(request());assert.equal(f.stats.queries,0);assert.equal(f.stats.completions,0);}));
test('all gates with unpaid evidence never complete',()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture({paid:false});assert.equal((await(await route(f.call).POST(request())).json()).kind,'unpaid');assert.equal(f.stats.completions,0);assert.equal(f.stats.balance,29);}));
for(const evidence of [{paidAt:null},{paidAt:'2026-01-01T00:15:01Z'},{paidAt:'2025-12-31T23:59:59Z'},{amount:1.03},{currency:'USD'},{providerChannel:'alipay'},{providerTransactionId:'OTHER'},{rawSummarySafe:{signatureVerified:false,timestampVerified:true,identityVerified:true}}])test(`invalid evidence ${JSON.stringify(evidence)} never credits`,()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},async()=>{const f=realServiceFixture({evidence});await route(f.call).POST(request());assert.equal(f.stats.completions,0);assert.equal(f.stats.balance,29);assert.equal(f.stats.ledger,0);}));
test('authenticated GET reflects live process gate, is no-store and invokes no business service',()=>isolatedEnv({PAYMENT_RECONCILIATION_SECRET:'CI-INTERNAL-NOT-REAL'},async()=>{let calls=0;const api=route(async()=>{calls++;throw Error('READ_ONLY_VIOLATION');});for(const value of [undefined,'false','garbage','true']){if(value===undefined)delete process.env.SNPAY_RECONCILIATION_EXECUTE_ENABLED;else process.env.SNPAY_RECONCILIATION_EXECUTE_ENABLED=value;const r=await api.GET(request());assert.deepEqual(await r.json(),{executeEnabled:value==='true'});assert.equal(r.headers.get('Cache-Control'),'no-store');}assert.equal((await api.GET(request('WRONG'))).status,403);assert.equal(calls,0);}));
test('worker missing secret does not scan; typo master/execute gates make zero network calls',async()=>{const env={SNPAY_RECONCILIATION_ENABLED:'true',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true',NEXT_PUBLIC_SUPABASE_URL:'https://db.test',SUPABASE_SECRET_KEY:'CI-KEY',JIANLIAN_INTERNAL_BASE_URL:'http://127.0.0.1:3001'};let calls=0;const fetchImpl=async()=>{calls++;throw Error('FORBIDDEN');};await runSnpayReconciliationWatcher({env,args:['--execute'],fetchImpl});assert.equal(calls,0);for(const value of ['TRUE','true ','garbage','false']){await runSnpayReconciliationWatcher({env:{...env,PAYMENT_RECONCILIATION_SECRET:'CI-SECRET',SNPAY_RECONCILIATION_ENABLED:value},args:['--execute'],fetchImpl});await runSnpayReconciliationWatcher({env:{...env,PAYMENT_RECONCILIATION_SECRET:'CI-SECRET',SNPAY_RECONCILIATION_EXECUTE_ENABLED:value},args:['--execute'],fetchImpl});}assert.equal(calls,0);});
const release='/www/releases/jianlian-shop-'+'a'.repeat(40);
const ready={app:true,worker:{SNPAY_RECONCILIATION_ENABLED:'true',SNPAY_RECONCILIATION_EXECUTE_ENABLED:'true'},service:{LoadState:'loaded',ActiveState:'inactive'},timer:{LoadState:'loaded',UnitFileState:'disabled',ActiveState:'inactive'},release,pm2:{status:'online',cwd:release,procCwd:release,script:release+'/node_modules/next/dist/bin/next'},authConsistent:true,permissions:true,unitMatches:true,channelsSafe:true,health:true};
test('readiness fails closed on unknown app gate, release drift, permissions/auth/health and active timer',()=>{assert.equal(readinessStatus(ready).READY_FOR_EXECUTE,'yes');for(const patch of [{app:null},{app:false},{unitMatches:false},{permissions:false},{authConsistent:false},{health:false},{channelsSafe:false},{timer:{...ready.timer,ActiveState:'active'}},{service:{...ready.service,DropInPaths:'/override'}},{pm2:{...ready.pm2,cwd:'/wrong'}}])assert.equal(readinessStatus({...ready,...patch}).READY_FOR_EXECUTE,'no');});
test('worker config parser refuses duplicates and preserves invalid boolean whitespace',()=>{assert.equal(parseConfig('SNPAY_RECONCILIATION_ENABLED=true ').SNPAY_RECONCILIATION_ENABLED,'true ');assert.throws(()=>parseConfig('A=true\nA=false'));assert.throws(()=>parseConfig('export A=true'));});
test('readiness tool and future deployment do not silently install/start worker',()=>{const text=readFileSync(new URL('../../scripts/ops/snpay-reconciliation-readiness.mjs',import.meta.url),'utf8');assert.ok(!text.includes('/200'));assert.ok(!text.includes('queryPayment'));assert.ok(!text.includes('completePayment'));assert.match(text,/method:'GET'/);const deploy=readFileSync(new URL('../../scripts/production-release.sh',import.meta.url),'utf8');assert.ok(!deploy.includes('systemctl'));assert.ok(!deploy.includes('snpay-reconciliation'));});
