/**
 * Mock data for Jianlian Shop
 *
 * This file contains all mock data used across the application.
 * When integrating Supabase in the future, replace these with
 * real API calls to the Supabase database.
 *
 * Future Supabase integration location:
 * - Products: query from `products` table
 * - Orders: query from `orders` table with user filter
 * - User: query from `profiles` table joined with auth.users
 * - Categories: query from `categories` table
 * - Admin stats: aggregate queries on orders table
 */

import {
  Product,
  Order,
  UserProfile,
  Category,
  AdminStats,
  AdminOrder,
} from "./types";

// ── Categories ──────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: "sim-cards",
    name: "国际电话卡",
    icon: "CreditCard",
    href: "/products/sim-cards",
    description: "全球国际电话卡，支持多国通话",
  },
  {
    id: "gift-cards",
    name: "礼品卡 / 充值卡",
    icon: "Gift",
    href: "/products/gift-cards",
    description: "各大平台礼品卡，即买即用",
  },
  {
    id: "digital-accounts",
    name: "数字账号服务",
    icon: "KeyRound",
    href: "/products/digital-accounts",
    description: "数字账号开通与续费服务",
  },
  {
    id: "ai-membership",
    name: "AI会员充值",
    icon: "Sparkles",
    href: "/products/ai-membership",
    description: "AI平台会员充值服务",
  },
  {
    id: "account-recharge",
    name: "账号充值",
    icon: "Wallet",
    href: "/products/account-recharge",
    description: "各类账号余额充值",
  },
];

// ── Products ───────────────────────────────────────────────

export const products: Product[] = [
  // 国际电话卡
  {
    id: "sim-001",
    name: "GiffGaff 白卡",
    category: "sim-cards",
    categoryLabel: "国际电话卡",
    description: "英国 GiffGaff 白卡，适合英国号码注册与收件使用",
    price: 69.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "physical",
    deliveryLabel: "快递发货",
    productType: "physical",
    listingStatus: "active",
    detail: "英国 GiffGaff 白卡，适合英国号码相关业务使用。当前库存为0，仅展示套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
    faq: [
      { question: "当前可以购买吗？", answer: "当前库存为0，暂不可购买。" },
      { question: "可以补货吗？", answer: "可以联系客服确认补货时间和批量需求。" },
    ],
  },
  {
    id: "sim-002",
    name: "GiffGaff 白卡（余额5英镑）",
    category: "sim-cards",
    categoryLabel: "国际电话卡",
    description: "英国 GiffGaff 白卡，含5英镑余额",
    price: 89.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "physical",
    deliveryLabel: "快递发货",
    productType: "physical",
    listingStatus: "active",
    detail: "英国 GiffGaff 白卡，含5英镑余额。当前库存为0，仅展示套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
    faq: [
      { question: "余额是多少？", answer: "该套餐包含5英镑余额。" },
    ],
  },
  {
    id: "sim-003",
    name: "GiffGaff 白卡（已激活余额15英镑）",
    category: "sim-cards",
    categoryLabel: "国际电话卡",
    description: "英国 GiffGaff 已激活白卡，含15英镑余额",
    price: 239.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "physical",
    deliveryLabel: "快递发货",
    productType: "physical",
    listingStatus: "active",
    detail: "英国 GiffGaff 已激活白卡，含15英镑余额。当前库存为0，仅展示套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
  },
  {
    id: "sim-us-001",
    name: "Ultra Mobile",
    category: "sim-cards",
    categoryLabel: "国际电话卡",
    description: "美国 Ultra Mobile 电话卡，适合美国号码相关业务使用",
    price: 138.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "physical",
    deliveryLabel: "快递发货",
    productType: "physical",
    listingStatus: "active",
    detail: "美国 Ultra Mobile 电话卡，适合美国号码相关业务使用。当前库存为0，仅展示套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
  },
  {
    id: "sim-004",
    name: "日韩通话卡 10天",
    category: "sim-cards",
    categoryLabel: "国际电话卡",
    description: "日本韩国通用通话卡，10天有效，含150分钟",
    price: 88.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-2小时",
    deliveryMethod: "physical",
    deliveryLabel: "快递发货",
    productType: "physical",
    listingStatus: "inactive",
  },
  // 礼品卡
  {
    id: "gift-apple-tr-500",
    name: "土耳其 App Store & iTunes 礼品卡 500 ₺ 里拉",
    category: "gift-cards",
    categoryLabel: "Apple 苹果 ID",
    description: "兑换卡属于一次性商品，售出后不支持退换 iCloud / Apple Music / App Store可用",
    price: 78.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "Apple 苹果 ID，土耳其 App Store & iTunes 礼品卡 500 ₺ 里拉。当前库存为0，仅展示价格和套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
  },
  {
    id: "gift-apple-us",
    name: "美国 App Store & iTunes 礼品卡",
    category: "gift-cards",
    categoryLabel: "Apple 苹果 ID",
    description: "兑换卡属于一次性商品，售出后不支持退换 iCloud / Apple Music / App Store可用",
    price: 14.84,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "美国区 App Store & iTunes 礼品卡。当前库存为0，仅展示价格区间和套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
  },
  {
    id: "gift-giffgaff-topup",
    name: "GiffGaff 充值",
    category: "gift-cards",
    categoryLabel: "GiffGaff",
    description: "GiffGaff 充值，支持10英镑、15英镑、20英镑档位",
    price: 107.8,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "GiffGaff 充值，库存为0，仅展示SKU档位和价格信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系客服确认。",
  },
  {
    id: "gift-001",
    name: "Apple Gift Card $50",
    category: "gift-cards",
    categoryLabel: "礼品卡",
    description: "苹果礼品卡50美元面值，App Store及iTunes通用",
    price: 368.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "5-30分钟",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "Apple Gift Card $50面值，适用于App Store、iTunes、Apple Music等苹果服务充值。",
    purchaseNotes: "购买后卡密将通过邮件发送，请确保邮箱地址正确。",
    faq: [
      { question: "如何使用礼品卡？", answer: "在App Store或iTunes中选择兑换，输入卡密即可。" },
      { question: "可以退款吗？", answer: "数字商品一经发出不支持退款。" },
    ],
  },
  {
    id: "gift-002",
    name: "Google Play Gift Card $25",
    category: "gift-cards",
    categoryLabel: "礼品卡",
    description: "Google Play礼品卡25美元面值",
    price: 188.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "5-30分钟",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "gift-003",
    name: "Steam Gift Card $20",
    category: "gift-cards",
    categoryLabel: "礼品卡",
    description: "Steam游戏平台礼品卡20美元面值",
    price: 148.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "5-30分钟",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "gift-004",
    name: "Amazon Gift Card $100",
    category: "gift-cards",
    categoryLabel: "礼品卡",
    description: "Amazon礼品卡100美元面值",
    price: 728.0,
    currency: "CNY",
    stockStatus: "low-stock",
    stockLabel: "库存紧张",
    processingTime: "30分钟-2小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  // 数字账号服务
  {
    id: "dig-001",
    name: "ChatGPT Plus 账号开通",
    category: "digital-accounts",
    categoryLabel: "数字账号服务",
    description: "ChatGPT Plus会员账号开通服务",
    price: 158.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-6小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "ChatGPT Plus会员账号开通，享受GPT-4模型访问权限，优先使用新功能。",
    purchaseNotes: "购买后账号信息将通过邮件发送，首次登录请修改密码。",
    faq: [
      { question: "账号有效期多久？", answer: "开通后一个月内有效，到期可续费。" },
    ],
  },
  {
    id: "dig-002",
    name: "Netflix Premium 账号",
    category: "digital-accounts",
    categoryLabel: "数字账号服务",
    description: "Netflix Premium会员账号，4K超清",
    price: 98.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-3小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "dig-003",
    name: "Spotify Premium 账号",
    category: "digital-accounts",
    categoryLabel: "数字账号服务",
    description: "Spotify Premium会员，无损音乐畅听",
    price: 68.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "暂时缺货",
    processingTime: "暂不可购买",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "inactive",
  },
  // AI会员充值
  {
    id: "ai-gpt-cdk-tr-plus-1m",
    name: "CDK【安卓IOS通用】土区IOS GPT Plus 一个月充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "土区 IOS GPT Plus 一个月充值 CDK，安卓 iOS 通用。",
    price: 89.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "CDK【安卓IOS通用】土区IOS GPT Plus 一个月充值。当前库存为0，仅展示价格和套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系在线客服确认。",
  },
  {
    id: "ai-claude-cdk-ng-pro-1m",
    name: "CDK【安卓IOS通用】尼区IOS claude pro 一个月充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "尼区 IOS Claude Pro 一个月充值 CDK，安卓 iOS 通用。",
    price: 116.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "库存：48",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "CDK【安卓IOS通用】尼区IOS claude pro 一个月充值。库存48。",
    purchaseNotes: "CDK 类商品属于一次性商品，售出后不支持无理由退换。",
  },
  {
    id: "ai-claude-cdk-ng-max-5x-1m",
    name: "CDK【安卓IOS通用】尼区IOS claude MAX 5X 一个月充值CDK",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "尼区 IOS Claude MAX 5X 一个月充值 CDK，安卓 iOS 通用。",
    price: 664.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "CDK【安卓IOS通用】尼区IOS claude MAX 5X 一个月充值CDK。当前库存为0，仅展示价格和套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系在线客服确认。",
  },
  {
    id: "ai-claude-cdk-ng-max-20x-1m",
    name: "CDK【安卓IOS通用】尼区IOS claude MAX 20X 一个月充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "尼区 IOS Claude MAX 20X 一个月充值 CDK，安卓 iOS 通用。",
    price: 1330.0,
    currency: "CNY",
    stockStatus: "out-of-stock",
    stockLabel: "库存：0",
    processingTime: "补货中",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "CDK【安卓IOS通用】尼区IOS claude MAX 20X 一个月充值。当前库存为0，仅展示价格和套餐信息。",
    purchaseNotes: "库存为0时暂不可购买。如需补货或批量购买，请联系在线客服确认。",
  },
  {
    id: "ai-grok-cdk-in-super-1m",
    name: "CDK【安卓IOS通用】印度区IOS Grok Super 一个月充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "印度区 IOS Grok Super 一个月充值 CDK，安卓 iOS 通用。",
    price: 67.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "库存：47",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "CDK【安卓IOS通用】印度区IOS Grok Super 一个月充值。库存47。",
    purchaseNotes: "CDK 类商品属于一次性商品，售出后不支持无理由退换。",
  },
  {
    id: "ai-gemini-google-one-pro-pixel",
    name: "Google One Pro (Pixel开通）",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "Google One Pro，Pixel 开通。",
    price: 18.9,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "库存：937",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "Google One Pro (Pixel开通）。库存937。",
    purchaseNotes: "数字商品属于一次性商品，售出后不支持无理由退换。",
  },
  {
    id: "ai-gemini-google-one-pro-pixel-1y",
    name: "Google One Pro (Pixel开通） 一年高权重成品号",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "Google One Pro，Pixel 开通，一年高权重成品号。",
    price: 26.4,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "库存：3",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "Google One Pro (Pixel开通） 一年高权重成品号。库存3。",
    purchaseNotes: "数字商品属于一次性商品，售出后不支持无理由退换。",
  },
  {
    id: "ai-001",
    name: "ChatGPT Plus 月费充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "ChatGPT Plus会员月费代充服务",
    price: 148.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
    detail: "为您的ChatGPT Plus账号代充月费，续费不断档，保持GPT-4访问权限。",
    purchaseNotes: "请在订单中填写您的ChatGPT账号邮箱，充值完成后将通知您。",
    faq: [
      { question: "充值多久到账？", answer: "通常1-12小时内完成充值。" },
    ],
  },
  {
    id: "ai-002",
    name: "Midjourney 会员充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "Midjourney AI绘画平台会员充值",
    price: 128.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-6小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "ai-003",
    name: "Claude Pro 会员充值",
    category: "ai-membership",
    categoryLabel: "AI会员充值",
    description: "Claude Pro会员月费代充服务",
    price: 168.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "1-12小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  // 账号充值
  {
    id: "rch-001",
    name: "Apple ID 余额充值 $10",
    category: "account-recharge",
    categoryLabel: "账号充值",
    description: "Apple ID余额充值10美元",
    price: 75.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "5-60分钟",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "rch-002",
    name: "Google Play 余额充值 $10",
    category: "account-recharge",
    categoryLabel: "账号充值",
    description: "Google Play余额充值10美元",
    price: 72.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "5-60分钟",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
  {
    id: "rch-003",
    name: "PayPal 余额充值 $20",
    category: "account-recharge",
    categoryLabel: "账号充值",
    description: "PayPal余额充值20美元",
    price: 148.0,
    currency: "CNY",
    stockStatus: "in-stock",
    stockLabel: "有货",
    processingTime: "30分钟-3小时",
    deliveryMethod: "digital",
    deliveryLabel: "在线交付",
    productType: "digital",
    listingStatus: "active",
  },
];

// ── Orders ──────────────────────────────────────────────────

export const orders: Order[] = [
  {
    id: "ord-001",
    orderNo: "JL20260601001",
    productName: "美国通话卡 30天套餐",
    productId: "sim-001",
    amount: 128.0,
    paymentStatus: "paid",
    paymentStatusLabel: "已付款",
    processingStatus: "completed",
    processingStatusLabel: "已完成",
    createdAt: "2026-06-01 14:30",
    contactInfo: "138****5678",
    shippingInfo: "已发货，快递单号：SF1234567890",
    productType: "physical",
  },
  {
    id: "ord-002",
    orderNo: "JL20260602002",
    productName: "Apple Gift Card $50",
    productId: "gift-001",
    amount: 368.0,
    paymentStatus: "paid",
    paymentStatusLabel: "已付款",
    processingStatus: "completed",
    processingStatusLabel: "已完成",
    createdAt: "2026-06-02 09:15",
    contactInfo: "test@example.com",
    shippingInfo: "卡密已发送至邮箱",
    productType: "digital",
  },
  {
    id: "ord-003",
    orderNo: "JL20260603003",
    productName: "ChatGPT Plus 月费充值",
    productId: "ai-001",
    amount: 148.0,
    paymentStatus: "pending",
    paymentStatusLabel: "待付款",
    processingStatus: "processing",
    processingStatusLabel: "处理中",
    createdAt: "2026-06-03 16:45",
    contactInfo: "user@mail.com",
    productType: "digital",
  },
  {
    id: "ord-004",
    orderNo: "JL20260604004",
    productName: "Google Play 余额充值 $10",
    productId: "rch-002",
    amount: 72.0,
    paymentStatus: "paid",
    paymentStatusLabel: "已付款",
    processingStatus: "processing",
    processingStatusLabel: "处理中",
    createdAt: "2026-06-04 08:20",
    contactInfo: "138****1234",
    productType: "digital",
  },
];

// ── User Profile (mock) ─────────────────────────────────────

export const mockUser: UserProfile = {
  id: "user-001",
  phone: "138****5678",
  email: "user@example.com",
  balance: 0.0,
  orderCount: 5,
  role: "user",
  roleLabel: "普通用户",
};

export const mockGuest: UserProfile = {
  id: "guest-000",
  phone: "",
  email: "",
  balance: 0.0,
  orderCount: 0,
  role: "guest",
  roleLabel: "游客",
};

// ── Admin Stats ─────────────────────────────────────────────

export const adminStats: AdminStats = {
  todayOrders: 12,
  pendingPaymentOrders: 4,
  pendingProcessingOrders: 6,
  completedOrders: 58,
  todayRevenue: 3680.0,
};

// ── Admin Orders (extended) ─────────────────────────────────

export const adminOrders: AdminOrder[] = [
  {
    ...orders[0],
    productCategory: "sim-cards",
    customerContact: "138****5678",
    paymentMethod: "支付宝",
  },
  {
    ...orders[1],
    productCategory: "gift-cards",
    customerContact: "test@example.com",
    paymentMethod: "微信支付",
  },
  {
    ...orders[2],
    productCategory: "ai-membership",
    customerContact: "user@mail.com",
    paymentMethod: "待支付",
  },
  {
    ...orders[3],
    productCategory: "account-recharge",
    customerContact: "138****1234",
    paymentMethod: "支付宝",
  },
];

// ── Announcement Text ───────────────────────────────────────

export const announcementText =
  "请牢记域名www.jianlian.shop，本站不提供任何中国大陆业务。网站出售的商品以及社媒服务仅限个人或团体合法电商拓客使用。严禁任何人利用购买的商品进行任何违法犯罪活动。消费者若使用本网站提供商品发生未经授权的违法犯罪行为所产生的一切责任，均由消费者自行承担，与本站制作者无关。特此声明！注意：在购买本网站提供的商品之前，消费者必须仔细阅读这些条款。消费者一旦购买，即视为完全同意本声明，无任何异议。";
