export type DajuProduct = { id: number; title: string; price: string; stock: number; sales: number; isAuto: boolean; cover: string | null; sortId: number | null };
export type DajuProductDetail = DajuProduct & { isSku: boolean; description: string | null; minQty: number; maxQty: number; specs: unknown[]; skuVariants: unknown[]; requiredInputs: string[] };
export type DajuBalance = { balance: string; name: string; totalSpent: string; totalOrders: number };
export type DajuOrder = { orderCode: string; requestId: string | null; quantity: number; unitPrice: string; totalPrice: string; balanceAfter: string | null; status: string; delivered: string[]; duplicate: boolean };
export function isPlainRecord(value: unknown): value is Record<string, unknown>;
export function parseDajuDecimal(value: unknown): string | null;
export function parseDajuProduct(value: unknown): DajuProduct | null;
export function parseDajuProductsResponse(value: unknown): DajuProduct[] | null;
export function parseDajuProductDetailResponse(value: unknown): DajuProductDetail | null;
export function parseDajuBalanceResponse(value: unknown): DajuBalance | null;
export function parseDajuDelivered(value: unknown): string[] | null;
export function parseDajuOrderResponse(value: unknown): DajuOrder | null;
export function parseDajuErrorResponse(value: unknown, httpStatus: number): { code: string };
export function classifyDajuPurchaseFailure(code: string): { state: "FAILED" | "PENDING" | "UNCERTAIN"; retryable: boolean };
export function createDajuRequestId(orderId: string, orderItemId: string): string | null;
export function redactDajuLogValue(value: unknown): Record<string, unknown>;
